- name: Database install
  hosts: all
  remote_user: root
  tasks:
    - apk:
       name: lighttpd
       state: present
       update_cache: yes
    - service:
       name: lighttpd
       enabled: yes
       state: started
