version: '3.6'

services:
    vsftpd-s3:
        build: ../node-ftp/docker/vsftpd-s3
        cap_add:
          - sys_admin
        devices:
          - /dev/fuse
        environment:
          - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          - FTPD_USERS=${FTPD_USERS}
        hostname: ${HOSTNAME}
        security_opt:
          - apparmor:unconfined
        network_mode: host
        restart: always
