version: '3.6'

services:
    vsftpd-s3:
        build: ../node-ftp/docker/vsftpd-s3
        cap_add:
          - sys_admin
        devices:
          - /dev/fuse
        security_opt:
          - apparmor:unconfined
        network_mode: host
        restart: always
