version: '3.6'

services:
    vsftpd-s3:
        build: ../ftp/docker/vsftpd-s3
        cap_add:
          - sys_admin
        devices:
          - /dev/fuse
        security_opt:
          - apparmor:unconfined
        labels:
          - SERVICE_21_NAME=${ENV}-${APP}-vsftpd-s3-ftp
          - SERVICE_21_CHECK_TCP=true
          - SERVICE_21_CHECK_INITIAL_STATUS=passing
          - SERVICE_22_IGNORE=true
          - SERVICE_65000_IGNORE=true
        ports:
          - 21:21
          - 65000:65000
        restart: always
        network_mode: host

networks:
    default:
        external:
            name: ${DOCKER_NETWORK}

