version: "3"

services:
  vsftpd-s3:
    build: ../ftp/docker/vsftpd-s3
    cap_add:
      - sys_admin
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    labels:
      - SERVICE_21_NAME=${ENV}-${APP}-vsftpd-s3-ftp
      - SERVICE_21_CHECK_TCP=true
      - SERVICE_21_CHECK_INITIAL_STATUS=passing
      - SERVICE_21_TAGS=urlprefix-:21 proto=tcp
      - SERVICE_22_NAME=${ENV}-${APP}-vsftpd-s3-sftp
      - SERVICE_22_CHECK_TCP=true
      - SERVICE_22_CHECK_INITIAL_STATUS=passing
      - SERVICE_22_TAGS=urlprefix-:22 proto=tcp
      - SERVICE_65000_IGNORE=true
    ports:
      - 21
      - 22
      - 65000:65000
    restart: always
    network_mode: host

networks:
  default:
    external:
      name: ${DOCKER_NETWORK}

