version: '3.6'

services:
  apm-server:
    build:
      args:
      - DOCKER_BUILD_DIR=docker/apm-server
      context: ..
      dockerfile: docker/apm-server/Dockerfile
    image: docker.elastic.co/apm/apm-server-oss:7.4.2
    command: -c apm-server.yml --strict.perms=false -e -E output.elasticsearch.hosts=["${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"] -E output.elasticsearch.protocol=${ELASTICSEARCH_PROTOCOL} -E output.elasticsearch.username=${ELASTICSEARCH_USERNAME} -E output.elasticsearch.password=${ELASTICSEARCH_PASSWORD} -E apm-server.register.ingest.pipeline.enabled=false
    labels:
    - SERVICE_8200_CHECK_HTTP=/healthcheck
    - SERVICE_8200_NAME=${COMPOSE_SERVICE_NAME}-apm-server-8200
    - SERVICE_8200_TAGS=${APM_SERVER_SERVICE_8200_TAGS}
    networks:
    - private
    - public
    ports:
    - 8200
    restart: always

networks:
  private:
    external: true
    name: ${DOCKER_NETWORK}
  public:
    external: true
    name: node
