- name: 'Install Python PIP'
  package: >
    name=py2-pip
    state=latest

- name: 'Install python-pathlib'
  pip: >
    name=pathlib
    state=latest

- name: "Discover NVMe EBS"
  disk_config:
    config: "{{ disk_additional_disks }}"
  register: __disk_config
  when: disk_discover_aws_nvme_ebs | default(True) | bool

- set_fact:
    disk_additional_disks: "{{ __disk_config['ansible_facts']['config'] }}"
  when: __disk_config is defined and __disk_config | success and 'ansible_facts' in __disk_config

- name: "Install parted"
  package:
    name: parted
    state: present
    use: '{{ disk_package_use }}'
  when: disk_additional_disks
  tags: ['disk', 'pkgs']

- name: "Install additional fs progs"
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ additional_fs_utils|default([]) }}"
  when: additional_fs_utils is defined
  tags: ['disk', 'pkgs']

- name: "Get disk alignment for disks"
  shell: |
    if
      [[ -e /sys/block/{{ item.disk | basename }}/queue/optimal_io_size && -e /sys/block/{{ item.disk | basename }}/alignment_offset && -e /sys/block/{{ item.disk | basename }}/queue/physical_block_size ]];
    then
      echo $[$(( ($(cat /sys/block/{{ item.disk | basename }}/queue/optimal_io_size) + $(cat /sys/block/{{ item.disk | basename }}/alignment_offset)) / $(cat /sys/block/{{ item.disk | basename }}/queue/physical_block_size) )) | 2048];
    else
      echo 2048;
    fi
  args:
    creates: '{{ item.part | default(item.disk + "1") }}'
    executable: '/bin/bash'
  with_items: '{{ disk_additional_disks }}'
  register: disk_offset
  tags: ['disk']

- name: "Ensure the disk exists"
  stat:
    path: '{{ item.disk }}'
  with_items: '{{ disk_additional_disks }}'
  register: disk_stat
  changed_when: False
  tags: ['disk']

- name: "Partition additional disks"
  shell: |
    if
        [ -b {{ item.disk }} ]
    then
        [ -b {{ item.part | default(item.disk + "1") }} ] || parted -a optimal --script "{{ item.disk }}" mklabel gpt mkpart primary {{ disk_offset.stdout|default("2048") }}s 100% && sleep 5 && partprobe {{ item.disk }}; sleep 5
    fi
  args:
    creates: '{{ item.part | default(item.disk + "1") }}'
    executable: '/bin/bash'
  with_items: '{{ disk_additional_disks }}'
  tags: ['disk']

- name: "Create filesystem on the first partition"
  filesystem:
    dev: '{{ item.0.part | default(item.0.disk + "1") }}'
    force: '{{ item.0.force|d(omit) }}'
    fstype: '{{ item.0.fstype }}'
    opts: '{{ item.0.fsopts|d(omit) }}'
  with_together:
    - '{{ disk_additional_disks }}'
    - '{{ disk_stat.results }}'
  when: item.1.stat.exists
  tags: ['disk']

- name: "Disable periodic fsck on ext3 or ext4 formatted disks"
  shell: tune2fs -c0 -i0 {{ item.0.part | default(item.0.disk + "1") }}
  with_together:
    - '{{ disk_additional_disks }}'
    - '{{ disk_stat.results }}'
  when: "disk_additional_disks and ( item.0.fstype == 'ext4' or item.0.fstype == 'ext3' ) and item.0.disable_periodic_fsck|default(false)|bool and item.1.stat.exists"
  tags: ['disk']

- name: "Ensure the mount directory exists"
  file:
    path: '{{ item.mount }}'
    owner: '{{ item.user | default("root") }}'
    group: '{{ item.group | default("root") }}'
    state: directory
  with_items: '{{ disk_additional_disks }}'
  tags: ['disk']

- name: "Get UUID for partition"
  command: blkid -s UUID -o value {{ item.0.part | default(item.0.disk + "1") }}
  check_mode: no
  register: disk_blkid
  with_together:
    - '{{ disk_additional_disks }}'
    - '{{ disk_stat.results }}'
  changed_when: False
  when: item.1.stat.exists
  tags: ['disk']

- name: "Mount additional disk"
  mount:
    name: '{{ item.0.mount }}'
    fstype: '{{ item.0.fstype }}'
    opts: '{{ item.0.mount_options|d(omit) }}'
    passno: '0'
    src: 'UUID={{ item.1.stdout }}'
    state: '{{ item.0.mount_state|d("mounted") }}'
  with_together:
    - '{{ disk_additional_disks }}'
    - '{{ disk_blkid.results }}'
    - '{{ disk_stat.results }}'
  when: item.2.stat.exists
  tags: ['disk']
  register: disks_handler_notify
  notify:
    - restart service

- name: "Ensure the permissions are set correctly"
  file:
    path: '{{ item.mount }}'
    owner: '{{ item.user | default("root") }}'
    group: '{{ item.group | default("root") }}'
    state: directory
  with_items: '{{ disk_additional_disks }}'
  tags: ['disk']
