version: '3.6'

services:
    opendj:
        build: ../auth/docker/opendj
        environment:
          - OPENDJ_JAVA_ARGS=-server -Xmx512m -XX:+UseG1GC
        labels:
          - SERVICE_389_NAME=${COMPOSE_PROJECT_NAME}_opendj-389
          - SERVICE_389_CHECK_INITITAL_STATUS=passing
          - SERVICE_389_CHECK_TCP=true
          - SERVICE_636_NAME=${COMPOSE_PROJECT_NAME}_opendj-636
          - SERVICE_636_CHECK_INITITAL_STATUS=passing
          - SERVICE_636_CHECK_TCP=true
          - SERVICE_4444_NAME=${COMPOSE_PROJECT_NAME}_opendj-4444
          - SERVICE_4444_CHECK_INITITAL_STATUS=passing
          - SERVICE_4444_CHECK_TCP=true
          - SERVICE_8989_NAME=${COMPOSE_PROJECT_NAME}_opendj-8989
          - SERVICE_8989_CHECK_INITITAL_STATUS=passing
          - SERVICE_8989_CHECK_TCP=true
        networks:
          - backend
          - frontend
        ports:
          - 389
          - 636
          - 4444
          - 8989
        restart: always
        volumes:
          - opendj:/opt/opendj/data
          - opendj-secrets:/var/secrets/opendj

volumes:
    opendj:
    opendj-secrets:

networks:
    backend:
        external:
            name: ${DOCKER_NETWORK}
    frontend:
        external:
            name: node

