version: '3.6'

services:
    consul:
        environment:
            CONSUL_LOCAL_CONFIG: '{"log_level": "warn"}'
    fabio:
        networks:
            frontend:
                aliases:
                  - 1001pharmacies.net
                  - aldrin.1001pharmacies.net
                  - api.1001pharmacies.net
                  - goodfellas.1001pharmacies.net
                  - medias.1001pharmacies.net
                  - v2.1001pharmacies.net
                  - www.1001pharmacies.net
                  - aldrin.tests.1001pharmacies.net
                  - api.tests.1001pharmacies.net
                  - goodfellas.tests.1001pharmacies.net
                  - medias.tests.1001pharmacies.net
                  - tests.1001pharmacies.net
                  - v2.tests.1001pharmacies.net
                  - www.tests.1001pharmacies.net
