version: "3"

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
        environment:
            - ES_JAVA_OPTS=-Xmx1024m -Xms1024m
            - xpack.security.enabled=false
            - xpack.monitoring.enabled=false
            - xpack.graph.enabled=false
            - xpack.watcher.enabled=false
            - cluster.name=elasticsearch-${ENV}
            - network.host=0.0.0.0
            - discovery.zen.minimum_master_nodes=1
            - http.cors.enabled=true
            - http.cors.allow-credentials=true
            - http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE
            - http.cors.max-age=0
            - http.cors.allow-origin="*"
            - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length
        labels:
            - SERVICE_9200_NAME=${ENV}-${APP}-elasticsearch-http
            - SERVICE_9200_CHECK_TCP=true
            - SERVICE_9200_CHECK_INITIAL_STATUS=passing
            - SERVICE_9200_TAGS=${SERVICE_ELASTICSEARCH_HTTP_TAGS}
            - SERVICE_9300_NAME=${ENV}-${APP}-elasticsearch-tcp
            - SERVICE_9300_CHECK_TCP=true
            - SERVICE_9300_CHECK_INITIAL_STATUS=passing
        ports:
            - 9200
            - 9300
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data
    kibana:
        depends_on:
            - elasticsearch
        image: docker.elastic.co/kibana/kibana:5.2.2
        environment:
            - ELASTICSEARCH_URL="http://elasticsearch:9200"
        labels:
            - SERVICE_5601_NAME=${ENV}-${APP}-kibana-http
            - SERVICE_5601_CHECK_TCP=true
            - SERVICE_5601_CHECK_INITIAL_STATUS=passing
            - SERVICE_5601_TAGS=${SERVICE_KIBANA_HTTP_TAGS}
        ports:
            - 5601
    mailcatcher:
        image: 1001pharmadev/mailcatcher
        labels:
            - SERVICE_1025_NAME=${ENV}-${APP}-mailcatcher-smtp
            - SERVICE_1025_CHECK_TCP=true
            - SERVICE_1025_CHECK_INITIAL_STATUS=passing
            - SERVICE_1080_NAME=${ENV}-${APP}-mailcatcher-http
            - SERVICE_1080_CHECK_TCP=true
            - SERVICE_1080_CHECK_INITIAL_STATUS=passing
            - SERVICE_1080_TAGS=${SERVICE_MAILCATCHER_HTTP_TAGS}
        ports:
            - 1025
            - 1080
    memcached:
        image: memcached:alpine
        labels:
            - SERVICE_11211_NAME=${ENV}-${APP}-memcached-tcp
            - SERVICE_11211_CHECK_TCP=true
            - SERVICE_11211_CHECK_INITIAL_STATUS=passing
        ports:
            - 11211
    mysql:
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        image: mariadb:latest
        labels:
            - SERVICE_3306_NAME=${ENV}-${APP}-mysql-tcp
        ports:
            - 3306
        volumes:
            - mysql:/var/lib/mysql
    rabbitmq:
        image: rabbitmq:management-alpine
        labels:
            - SERVICE_4369_IGNORE=true
            - SERVICE_5671_IGNORE=true
            - SERVICE_5672_NAME=${ENV}-${APP}-rabbitmq-amqp
            - SERVICE_5672_CHECK_TCP=true
            - SERVICE_5672_CHECK_INITIAL_STATUS=passing
            - SERVICE_15671_IGNORE=true
            - SERVICE_15672_NAME=${ENV}-${APP}-rabbitmq-http
            - SERVICE_15672_CHECK_TCP=true
            - SERVICE_15672_CHECK_INITIAL_STATUS=passing
            - SERVICE_15672_TAGS=${SERVICE_RABBITMQ_HTTP_TAGS}
            - SERVICE_25672_IGNORE=true
        ports:
            - 5672
            - 15672
        volumes:
            - rabbitmq:/var/lib/rabbitmq
    redis:
        image: redis:alpine
        labels:
            - SERVICE_6379_NAME=${ENV}-${APP}-redis-tcp
            - SERVICE_6379_CHECK_TCP=true
            - SERVICE_6379_CHECK_INITIAL_STATUS=passing
        ports:
            - 6379
    ssh-agent:
        image: 1001pharmadev/ssh-agent:latest
        volumes:
            - ssh-agent:/tmp/ssh-agent
    toggle-api:
        depends_on:
          - redis
        image: 1001pharmadev/toggle-api
        labels:
            - SERVICE_80_NAME=${ENV}-${APP}-toggle-api-http
            - SERVICE_80_CHECK_TCP=true
            - SERVICE_80_CHECK_INITIAL_STATUS=passing
            - SERVICE_80_TAGS=${SERVICE_TOGGLE_API_HTTP_TAGS}
        environment:
          - TOGGLE__REDIS_DSN=tcp://redis:6379
        ports:
            - 80
    toggle-ui:
        depends_on:
          - toggle-api
        image: 1001pharmadev/toggle-ui
        labels:
            - SERVICE_80_NAME=${ENV}-${APP}-toggle-ui-http
            - SERVICE_80_CHECK_TCP=true
            - SERVICE_80_CHECK_INITIAL_STATUS=passing
            - SERVICE_80_TAGS=${SERVICE_TOGGLE_UI_HTTP_TAGS}
        ports:
            - 80
        volumes:
          - ./docker/toggle/ui/config.js:/var/www/html/web/js/config.js

volumes:
    elasticsearch:
    mysql:
    rabbitmq:
    ssh-agent:

networks:
    default:
        external:
            name: ${DOCKER_NETWORK}
