version: "3"

services:
  drone-agent:
    image: drone/agent:0.8
    command: agent
    depends_on:
      - drone-server
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_MAX_PROCS=${DRONE_MAX_PROCS}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  drone-server:
    image: drone/drone:0.8
    environment:
      - DRONE_OPEN=true
      - DRONE_ORGS=${DRONE_ORGS}
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_ADMIN=${DRONE_ADMIN}
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
      - DRONE_GITHUB_PRIVATE_MODE=${DRONE_GITHUB_PRIVATE_MODE}
      - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}
      - DRONE_SECRET=${DRONE_SECRET}
    labels:
      - SERVICE_8000_NAME=${ENV}-${APP}-drone-server-http
      - SERVICE_8000_CHECK_TCP=true
      - SERVICE_8000_CHECK_INITIAL_STATUS=passing
      - SERVICE_8000_TAGS=${SERVICE_DRONE_HTTP_TAGS}
      - SERVICE_9000_NAME=${ENV}-${APP}-drone-server-grpc
      - SERVICE_9000_CHECK_TCP=true
      - SERVICE_9000_CHECK_INITIAL_STATUS=passing
    ports:
      - 8000
      - 9000
    restart: always
    volumes:
      - drone:/var/lib/drone/

volumes:
    drone:

networks:
  default:
    external:
      name: ${DOCKER_NETWORK}

