---
# file: tasks/files.yml

- name: files - copy files
  with_items:
    - /etc/profile.d/rc.sh
    - /etc/profile.d/rc_functions.sh
  copy: src=../files/{{item}} dest={{item}} owner=root group=root mode=0644
  become: yes

- name: files - copy binary files
  with_items:
    - /etc/init.d/zram
  copy: src=../files/{{item}} dest={{item}} owner=root group=root mode=0755
  become: yes

- name: files - copy systemd files
  with_items:
    - /etc/systemd/system/zram.service
  copy: src=../files/{{item}} dest={{item}} owner=root group=root mode=0644
  when: ansible_service_mgr == "systemd"
  become: yes

