---
# file: tasks/git.yml

- name: git - clone repositories
  with_items: "{{ hosts_git_repositories|default([]) }}"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest|default('/src') }}"
    remote: "{{ item.remote|default('origin') }}"
    version: "{{ item.version|default('HEAD') }}"
