---
# file: playbook.yml

# bootstrap hosts
- hosts: all
  gather_facts: false
  pre_tasks:
  - name: raw - install ansible requirements for alpine linux
    raw: "[ -f /etc/alpine-release ] && /sbin/apk update && { which python >/dev/null 2>&1 || /sbin/apk add python; } && { which sudo >/dev/null 2>&1 || /sbin/apk add sudo; } && { /bin/tar --version 2>/dev/null |grep busybox >/dev/null && /sbin/apk add tar; } && { ls /usr/lib/ssh/sftp-server >/dev/null 2>&1 || /sbin/apk add openssh-sftp-server; } || true"

# install default packages and user settings
- include: playbooks/hosts.yml
  tags:
  - hosts

# install docker
- include: playbooks/docker.yml
  tags:
  - docker
