version: '3.6'

services:
  drone-runner-docker:
    image: drone/drone-runner-docker:1.1.0
    depends_on:
    - drone
    environment:
    # - DRONE_DEBUG=true
    # - DRONE_TRACE=true
    - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
    - DRONE_RPC_HOST=drone
    - DRONE_RPC_PROTO=http
    - DRONE_RUNNER_CAPACITY=${DRONE_RUNNER_CAPACITY}
    - DRONE_RUNNER_NAME=${HOSTNAME}
    labels:
    - SERVICE_3000_IGNORE=true
    networks:
    - private
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

networks:
  private:
      external: true
      name: ${DOCKER_NETWORK}
