version: '3.6'

services:
  drone:
    image: drone/drone:1.6.4
    environment:
    - DRONE_GIT_ALWAYS_AUTH=false
    - DRONE_GITHUB_SERVER=https://github.com
    - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
    - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
    - DRONE_LOGS_COLOR=true
    # - DRONE_LOGS_DEBUG=true
    - DRONE_LOGS_PRETTY=true
    # - DRONE_LOGS_TRACE=true
    - DRONE_PROMETHEUS_ANONYMOUS_ACCESS=true
    - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
    - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
    - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
    - DRONE_TLS_AUTOCERT=true
    - DRONE_USER_CREATE=${DRONE_USER_CREATE}
    - DRONE_USER_FILTER=${DRONE_USER_FILTER}
    labels:
    - SERVICE_80_NAME=${COMPOSE_SERVICE_NAME}-drone-80
    - SERVICE_80_CHECK_TCP=true
    - SERVICE_80_CHECK_INITIAL_STATUS=passing
    - SERVICE_80_TAGS=${DRONE_SERVER_SERVICE_80_TAGS}
    - SERVICE_443_IGNORE=true
    networks:
     - private
     - public
    ports:
    - 80
    - 443
    restart: always
    volumes:
    - drone:/data

volumes:
  drone:

networks:
  private:
      external: true
      name: ${DOCKER_NETWORK}
  public:
    external: true
    name: node
