version: '3.6'

services:
    redmine:
        image: sameersbn/redmine:latest
        # command: /bin/sh -c "crontab -l |sed 's|@hourly|@hourly cd /home/redmine/data/files/1001Pharmacies \&\& git fetch -q --all -p \&\&|' |crontab"
        environment:
          - DB_ADAPTER=mysql2
          - DB_HOST=mysql
          - DB_NAME=redmine
          - DB_USER=redmine
          - DB_PASS=redmine
          - REDMINE_FETCH_COMMITS=hourly
          - SMTP_DOMAIN=${SMTP_DOMAIN}
          - SMTP_USER=${SMTP_USER}
          - SMTP_PASS=${SMTP_PASS}
          - TZ=Europe/Paris
        labels:
          - SERVICE_80_NAME=${COMPOSE_PROJECT_NAME}_redmine-80
          - SERVICE_80_CHECK_TCP=true
          - SERVICE_80_CHECK_INITIAL_STATUS=passing
          - SERVICE_80_TAGS=${SERVICE_REDMINE_HTTP_TAGS}
          - SERVICE_443_IGNORE=true
        networks:
          - backend
          - frontend
        ports:
          - 80
        restart: always
        volumes:
          - redmine:/home/redmine/data
    static:
        image: nginx:alpine
        command: /bin/sh -c "sed -i 's|index  index.html index.htm;|index  index.html index.htm;\n        autoindex on;|' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        labels:
          - SERVICE_80_NAME=${COMPOSE_PROJECT_NAME}_static-80
          - SERVICE_80_CHECK_TCP=true
          - SERVICE_80_CHECK_INITIAL_STATUS=passing
          - SERVICE_80_TAGS=${SERVICE_STATIC_HTTP_TAGS}
        networks:
          - backend
          - frontend
        ports:
          - 80
        restart: always
        volumes:
          - static:/usr/share/nginx/html:ro

volumes:
    redmine:
    static:

networks:
    backend:
        external:
            name: ${DOCKER_NETWORK}
    frontend:
        external:
            name: node

