version: "3"

services:
  redmine:
    image: redmine
    #    crontab is not available in redmine image
    #    command: /bin/sh -c '(crontab -u redmine -l \
    #                             |grep -v "cd /usr/src/redmine/files/1001Pharmacies && git fetch -q --all -p" \
    #                             |grep -v "cd /usr/src/redmine && ruby script/runner Repository.fetch_changesets -e production" \
    #                             && echo "* * * * * cd /usr/src/redmine/files/1001Pharmacies && git fetch -q --all -p" \
    #                             && echo "* * * * * sleep 10 && cd /usr/src/redmine && ruby script/runner Repository.fetch_changesets -e production" \
    #                         ) |crontab -u redmine - \
    #                         && rake server && rails server -b 0.0.0.0'
    environment:
      - REDMINE_DB_MYSQL=mysql
      - REDMINE_DB_DATABASE=redmine
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_PASSWORD=redmine
    labels:
      - SERVICE_3000_NAME=${ENV}-${APP}-redmine-http
      - SERVICE_3000_CHECK_TCP=true
      - SERVICE_3000_CHECK_INITIAL_STATUS=passing
      - SERVICE_3000_TAGS=${SERVICE_REDMINE_HTTP_TAGS}
    ports:
      - 3000
    restart: always
    volumes:
        - redmine:/usr/src/redmine/files
        - redmine-plugins:/usr/src/redmine/plugins
  static:
    image: nginx:alpine
    command: /bin/sh -c "sed -i 's|index  index.html index.htm;|index  index.html index.htm;\n        autoindex on;|' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    labels:
      - SERVICE_80_NAME=${ENV}-${APP}-static-http
      - SERVICE_80_CHECK_TCP=true
      - SERVICE_80_CHECK_INITIAL_STATUS=passing
      - SERVICE_80_TAGS=${SERVICE_STATIC_HTTP_TAGS}
    ports:
      - 80
    restart: always
    volumes:
      - static:/usr/share/nginx/html:ro

volumes:
    redmine:
    redmine-plugins:
    static:

networks:
  default:
    external:
      name: ${DOCKER_NETWORK}

